# Generated by Django 3.0.6 on 2021-07-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('portfolio', '0002_auto_20210709_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='f_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='user.Field'),
        ),
    ]
