# Generated by Django 3.0.6 on 2021-08-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('portfolio', '0004_auto_20210730_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='field_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='user.Field'),
        ),
    ]
